---
name: Params-Clean
version: 0.9.2
author:
  - 'David Green <plato@cpan.org>'
abstract: Clean and simple parsing of args by position/name/flag/list/type
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Devel::Caller::Perl: 0
  UID: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Params::Clean:
    file: lib/Params/Clean.pm
    version: 0.9.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
